### ISSUE TITLE
developブランチがクラッシュする

### ISSUE THREAD

**Issue by tokku5552** [mosynthkey/Melissa#20]
エラー内容は以下の通り。
Assertion failed!

Program:....\Melissa.exe
File ....\Submodule\so...\AAFilter.cpp
Line:121

Expression:cutoffFreq>=0

For information on how your program can cause an assertion failure, see the Visual C++ documentation on asserts

(Press Retry to debug the application - JIT must be enabled)

**Comment by tokku5552** [comment]
masterブランチとdevelopeブランチCompareしても同じなのに・・・

**Comment by mosynthkey** [comment]
これどういう状況で発生しましたか？

**Comment by tokku5552** [comment]
ブランチをdevelopeにしてビルドしただけです・・・　masterにしてビルドすると発生しない

**Comment by mosynthkey** [comment]
https://github.com/mosynthkey/Melissa/commit/d240c8eec920e81e055656d02dd2588dd51d7fed
このcommitがdevelopに入ってなかったです！(リリース直前に入れたコミットでした…ｗ)今はmergeしたので大丈夫だと思います。

**Comment by tokku5552** [comment]
developeブランチでReleaseビルドしたら無事ビルドできるようになっていました。Debugは相変わらずWindowsだと失敗しますが・・・

**Comment by tokku5552** [comment]
違いました、d240c8eこのcommitをdevelopeにマージした後はdevelopeでDebugもReleaseもビルドうまくいきますが、85b763eの変更でDebugもReleaseも失敗するようになっていました。

**Comment by mosynthkey** [comment]
失敗するはクラッシュする感じですか？
気軽に立ち上げられるWin環境がないのでちょっとあとになっちゃうかもですが見てみます〜

**Comment by tokku5552** [comment]
そもそもビルドに失敗する感じですね・・・Xcodeだとビルドはうまくいくんだけど・・・

**Comment by tokku5552** [comment]
すみません。jucerを読み直したら治りました・・・
