### ISSUE TITLE
no Fonts

### ISSUE THREAD

**Issue by tank-trax** [mosynthkey/Melissa#23]
Operating System: Debian GNU/Linux 11
KDE Plasma Version: 5.20.5
KDE Frameworks Version: 5.78.0
Qt Version: 5.15.2
Kernel Version: 5.10.0-7-rt-amd64
OS Type: 64-bit

I am able to build the app but am not getting fonts. I was wondering if you had any clues?

Thanks

![image](https://user-images.githubusercontent.com/41337033/121763719-3db12e00-cb0c-11eb-9748-37f5120eb194.png)

**Comment by mosynthkey** [comment]
Thank you very much for letting me know this issue.
I'll check this, but I don't have Linux machine, so it may take some time.

**Comment by tank-trax** [comment]
if there is anything I can do to help let me know... any clues as to how the fonts work on Windows/OSX would be helpful.... I may be able to discover a solution

thanks!!

**Comment by mosynthkey** [comment]
@tank-trax 
I'm sorry for keep you waiting. Today I released Melissa version 2.5, that may fix this issue.
Could you pull the master branch and check this?

If this doesn't work, please try the following:
(1) Open ~/.config/Melissa/Settings.json 
If this doesn't exist, please launch Melissa and quit it. This file will be automatically created when quitting.
(2) Set "font_name" to the name of the font installed on your system.
(3) Launch Melissa again.

I'm sorry to bother you. I hope this helps.

**Comment by tank-trax** [comment]
no bother... and thanks for the reply

I built the latest version and it segfaulted, then built the Debug and ran gdb

here is what it returned....

```
(gdb) run
Starting program: /home/studio/dev/git/Melissa/Melissa/Builds/LinuxMakefile/build/Melissa 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
juce::CharPointer_UTF8::isEmpty (this=0x55555602cd98 <juce::juce_xmltextContentAttributeName>)
    at /home/studio/JUCE/modules/juce_core/text/juce_CharPointer_UTF8.h:73
73          bool isEmpty() const noexcept                { return *data == 0; }
```

**Comment by KottV** [comment]
it crashes on
https://github.com/mosynthkey/Melissa/blob/f37683de795fe20f40037412d634d5fe6e41ba19/Melissa/Source/MelissaDataSource.cpp#L439

i don't know why, maybe JUCE Linux specific bug

**Comment by mosynthkey** [comment]
Thank you for the information. I solved this problem by changing the font initialization sequence.
(I tested this on Debian GNU/Linux 11.)
So could you check this on **develop** branch?

**Comment by KottV** [comment]
Yes, it works perfect now.
Thank You so much!

**Comment by tank-trax** [comment]
works here too. thank you.

![image](https://user-images.githubusercontent.com/41337033/129282762-0356b4a0-ed16-4e1b-80d8-00bc13280b69.png)

**Comment by davidhealey** [comment]
@tank-trax Could you explain what you needed to do to build on Debian? I'm familiar with using Projucer and running make files, but I'm hitting errors. The first one is about soundtouch, I have the libsoundtouch-dev package installed but clearly I'm missing something.

**Comment by tank-trax** [comment]
> @tank-trax Could you explain what you needed to do to build on Debian? I'm familiar with using Projucer and running make files, but I'm hitting errors. The first one is about soundtouch, I have the libsoundtouch-dev package installed but clearly I'm missing something.

did you `git submodule update --init --recursive`?

**Comment by davidhealey** [comment]
@tank-trax I just did `git submodule update --init` because that's what it says in the repo readme, is the --recursive a necessity here?

**Comment by tank-trax** [comment]
> @tank-trax I just did `git submodule update --init` because that's what it says in the repo readme, is the --recursive a necessity here?

before you do it change this line in `.gitmodules`

```
#	url = git@github.com:nlohmann/json.git
	url = https://github.com/nlohmann/json.git
```

**Comment by davidhealey** [comment]
@tank-trax Thanks, that seems to have got me past the soundtouch error, I did the `--recursive` just in case. Now I'm hitting an error about spleeter.

```
In file included from ../../../ThirdParty/spleet/input_file.cpp:11:
../../../ThirdParty/spleet/input_file.h:15:10: fatal error: spleeter/spleeter.h: No such file or directory
   15 | #include "spleeter/spleeter.h"
```

That file seems to be within `spleetercpp/include/spleeter`. Do I need to edit the juicer file?

**Comment by davidhealey** [comment]
Nope it seems the included library is only for MacOS. So I guess I need to build that too? What did you do?

**Comment by tank-trax** [comment]
@davidhealey 

I added `-I../../../ThirdParty/spleet/` to Extra Compiler Flags

**Comment by davidhealey** [comment]
@tank-trax I get the same error but I used `-I../../../ThirdParty/spleeterpp/include`. I think this is because the included libspleeter.a was built for MacOS.

**Comment by tank-trax** [comment]
I built it and am now getting

```
Linking Melissa - App
/usr/bin/ld: cannot find -ld_classic: No such file or directory
/usr/bin/ld: cannot find -ltensorflow: No such file or directory
/usr/bin/ld: cannot find -ltensorflow_framework: No such file or directory
collect2: error: ld returned 1 exit status
make: *** [Makefile:154: build/Melissa] Error 1
```

**Comment by davidhealey** [comment]
Did you add the linker flags?

**Comment by tank-trax** [comment]
I don't think we need `ld_classic` either. That seems iOS specific.

**Comment by davidhealey** [comment]
> built spleeterpp from https://github.com/gvne/spleeterpp

Are you building the master branch? I get an error

```
/home/dave/Desktop/spleeterpp/test/artff/test_artff.cc:9:23: error: ‘sleep_for’ is not a member of ‘std::this_thread’
    9 |     std::this_thread::sleep_for(std::chrono::seconds(1));
      |                       ^~~~~~~~~
gmake[2]: *** [test/artff/CMakeFiles/test_artff.dir/build.make:76: test/artff/CMakeFiles/test_artff.dir/test_artff.cc.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:1408: test/artff/CMakeFiles/test_artff.dir/all] Error 2
gmake: *** [Makefile:136: all] Error 2
```

**Comment by tank-trax** [comment]
@davidhealey 

had to add `#include<thread>` to **test_artff.cc**

**Comment by tank-trax** [comment]
Success.

Download TensorFlow C library from https://www.tensorflow.org/install/lang_c

Extract to `...Melissa/ThirdParty/`

Change the following to:

**Extra Compiler Flags**
```
-I../../../ThirdParty/spleeterpp/include
-I../../../ThirdParty/libtensorflow-cpu-linux-x86_64-2.15.0/include
-I../../../ThirdParty/spleet/
```
**Extra Linker Flags**
```
-L../../../ThirdParty/spleeterpp/lib
-L../../../ThirdParty/libtensorflow-cpu-linux-x86_64-2.15.0/lib
```

Must navigate to `...ThirdParty/libtensorflow-cpu-linux-x86_64-2.15.0/lib/`

Copy files to `/usr/local/lib/` and run `sudo ldconfig`

![image](https://github.com/mosynthkey/Melissa/assets/41337033/b42665fb-35f1-460e-b221-947fdc05df85)

**Comment by davidhealey** [comment]
@tank-trax Thanks it's working here. I also had to add this to the External Libraries to Link section

```
spleeter
spleeter_common
tensorflow
tensorflow_framework
```

When I first loaded the program it segfaulted. In the debugger I could see this was caused by the CURL update check. So in Projucer >> Modules >> juce_core I disabled JUCE_USE_CURL and now the program runs.

Any idea what the difference is between Melissa and Melissa Lite?

**Comment by tank-trax** [comment]
No segfaults here. However I failed to mention that...

I enabled JACK in juce_audio_devices
and disabled CURL and JUCE_WEB_BROWSER

I also added to the External Libraries to Link

```
spleeter
spleeter_common
tensorflow
tensorflow_framework
```
And Edit->Settings

```
JUCE_DISPLAY_SPLASH_SCREEN=0
JUCE_REPORT_APP_USAGE=0
LINUX=1
JUCE_MODAL_LOOPS_PERMITTED=1
```

to Preprocessor Defintions

Sorry if I failed to mention that.

I think I will test if symbols are exposed.

**Comment by davidhealey** [comment]
@tank-trax Aha perfect, thanks for the extra info.

**Comment by mosynthkey** [comment]
Sorry, the Linux Build for Melissa is not currently maintained. Thank you for trying in such a situation.

The difference between Melissa and Melissa Lite is whether the audio separation feature is implemented or not; Melissa Lite does not have audio signal separation, so there is no need to link spleeter or tensorflow. (I have never linked spleeter or sensorflow on Linux, so I am sorry I cannot guide you on how to do it.)

**Comment by davidhealey** [comment]
> Sorry, the Linux Build for Melissa is not currently maintained. Thank you for trying in such a situation.
> 
> The difference between Melissa and Melissa Lite is whether the audio separation feature is implemented or not; Melissa Lite does not have audio signal separation, so there is no need to link spleeter or tensorflow. (I have never linked spleeter or sensorflow on Linux, so I am sorry I cannot guide you on how to do it.)

Hi thanks,

We have it working now :) Do you plan to add zoom for the waveform? Is there a way to move markers to a different position?

**Comment by mosynthkey** [comment]
> Do you plan to add zoom for the waveform? Is there a way to move markers to a different position?
Yes, these two tasks are planned for implementation in a future update. (#30 and #47.)
Thank you for requests!

**Comment by tank-trax** [comment]
@mosynthkey Thanks for showing up Apologies for using your Issue tracker as a chat room. :-) .

It's building well here on Debian 12. I think I may fork your repo.

@davidhealey 

you can add the following to the Release Exporter to help clean up exposed symbols

```
-fvisibility=hidden
-fdata-sections -ffunction-sections -Wl,--gc-sections -Wl,-O1 -Wl,--as-needed -Wl,--strip-all -fPIC
```
as so

![image](https://github.com/mosynthkey/Melissa/assets/41337033/66a66794-f896-4064-bbad-4dcb03d9c2e3)

**Comment by tank-trax** [comment]
the extra -fPIC on Compiler Flags cleaned up a bit extra

**Comment by tank-trax** [comment]
```
objdump -T Melissa | grep ' g '
0000000000903ca0 g    D  .bss   0000000000000000  Base        _end
00000000008d6648 g    D  .bss   0000000000000000  Base        __bss_start
00000000008d6680 g    DO .bss   0000000000000110 (GLIBCXX_3.4) _ZSt4cerr
00000000008d6648 g    D  .data  0000000000000000  Base        _edata
00000000008d6660 g    DO .bss   0000000000000001 (GLIBC_2.32) __libc_single_threaded
```
```
nm --demangle Melissa
nm: Melissa: no symbols
```
