### ISSUE TITLE
Translate website and issues in english

### ISSUE THREAD

**Issue by teopost** [mosynthkey/Melissa#28]
I suggest writing the content of the official site in English to increase the visibility!
This software is beautiful
Well done

**Comment by mosynthkey** [comment]
Thank you very much! I'll do that :)
How do you find Melissa?

**Comment by teopost** [comment]
Google search

**Comment by teopost** [comment]
Hi @mosynthkey,
   I renew my suggestion

**Comment by mosynthkey** [comment]
https://mosynthkey.github.io/Melissa/index_en.html
English website is now available!
