### ISSUE TITLE
Playlist is not played in order

### ISSUE THREAD

**Issue by teopost** [mosynthkey/Melissa#29]
The playlist is no player in order.

In the below sample, "Parallel Universe" is played after "Suck my kiss" and Scar Tissue is Skipped

![image](https://user-images.githubusercontent.com/2573389/138587025-7a963b2a-6110-44d0-9b8c-d2bb3bf32b74.png)

**Comment by mosynthkey** [comment]
I'm sorry for the late reply and the inconvenience. 
Today I released Melissa V2.5.2, which addresses this issue. Could you update to the latest?
