### ISSUE TITLE
Melissa don't start

### ISSUE THREAD

**Issue by teopost** [mosynthkey/Melissa#36]
Hi,
   after the last update of the operating system, melissa does not start anymore.
Even after a reinstall

**Comment by mosynthkey** [comment]
@teopost 
Thank you for letting me the issue. Could you tell me the version you installed and your OS version?

**Comment by teopost** [comment]
macOS Monterey 12.5.1
Melissa 2.5.2

**Comment by mosynthkey** [comment]
Thank you for the information. I'll check this with the same OS version.

**Comment by mosynthkey** [comment]
@teopost 
I tried, but couldn't reproduce this issuse.
Could you temporarily rename the Melissa's settings file (~/Library/Melissa/Settings.json) and check if it starts?

**Comment by teopost** [comment]
I renamed the file but Melissa won't start

<img width="578" alt="immagine" src="https://user-images.githubusercontent.com/2573389/188311614-eee3f695-4ccb-4bfa-b93a-c57e3937c715.png">

Is there any debugging I could turn on?

**Comment by mosynthkey** [comment]
@teopost 
I'm sorry for the inocnvenience.
Currently Melissa doesn't have debbuging switch.
Can you find a crash report on macOS's terminal app?

And could you tell me your hardware information?
(The name of model of your mac, the audio device you use, etc...)

**Comment by teopost** [comment]
Hi @mosynthkey ,
   I don't know why, but after a mac reboot it now works.
Thanks for the support and sorry for the inconvenience.

**Comment by ono-korg** [comment]
Thank you for the feedback. Glad to hear your report, but it sounds like something wrong is happening. I will continue to investigate👍

**Comment by mosynthkey** [comment]
I’m glad to hear that this problem is solved. But something seems to be wrong, I’ll continue to investigate the cause of issue.
