### ISSUE TITLE
macOS 13.1 で使用すると日本語が文字化けする

### ISSUE THREAD

**Issue by ghetto2199** [mosynthkey/Melissa#38]
macOS 13.1 で使用すると日本語が文字化けします

**Comment by mosynthkey** [comment]
@ghetto2199 Melissaでは標準フォントで游ゴシック体を使っているのですが、OSが自動でフォントをアンインストールすることがあるそうです。
https://good-web-design.com/column/mac-yu-gothic-download

現状の解決方法として、以下の手順をお試しいただけますと幸いです。
1. Melissaを終了する
2. 游ゴシック体をインストールしていただく (上記URLを参考にお願いします)
3. ~/Library/Melissa/Settings.jsonを一旦削除
4. Melissaを再起動する

次のVersionで游ゴシック体以外も使用の候補とするように改善します。
お手数をおかけしますが、よろしくお願いいたします。

**Comment by ghetto2199** [comment]
上記の手順で解消することを確認いたしました。
本件クローズします。
