### ISSUE TITLE
Crash when I turn off my hx stomp device

### ISSUE THREAD

**Issue by teopost** [mosynthkey/Melissa#40]
When I turn off the sound card of the connected foot pedal (hx stomp), Melissa crashes.

I'm attach the Mac crash report

PS: Congrats on the latest great release

[CrashReport.txt](https://github.com/mosynthkey/Melissa/files/10418372/CrashReport.txt)

**Comment by mosynthkey** [comment]
Hi,

Thank you for letting me know the issue.
I addressed this issue, so could you check by installing this version? (v3.0.1)

https://drive.google.com/file/d/1QG25pcW4mvXG-NZ6_sQvOjCxlMjLcZZH/view?usp=sharing

**Comment by teopost** [comment]
Tested. Now work fine!

**Comment by mosynthkey** [comment]
Thank you very much for your cooperation :)
