### ISSUE TITLE
最新版をチェックが機能していない

### ISSUE THREAD

**Issue by taji-ex** [mosynthkey/Melissa#43]
Melissa Version 3.0.0
Platform M1 MacBook Pro 16

左上のメニューから最新版をチェックを押下しても最新版と言われる。

**Comment by mosynthkey** [comment]
ご報告ありがとうございます。こちらのmacでv3.0.0でテストしたのですが、再現できませんでした。
類似の報告がないか等、引き続き調査させていただきます。

**Comment by mosynthkey** [comment]
最新で問題ないようですので一旦closeします。
