### ISSUE TITLE
終了のショートカットが機能していない

### ISSUE THREAD

**Issue by taji-ex** [mosynthkey/Melissa#44]
Melissa Version 3.1.0(3.0.0でも同様でした)
Platform M1 MacBook Pro 16

Cmd+qで終了されない。

出来ればですが、Macでは×を押しても終了されない動作が好ましいと思います。
x=Cmd+w(ウィンドウを閉じる)
Cmd+qで終了される。

**Comment by mosynthkey** [comment]
ありがとうございます。こちらも対応させていただきます！
