### ISSUE TITLE
音量が保存されない

### ISSUE THREAD

**Issue by taji-ex** [mosynthkey/Melissa#45]
Melissa Version 3.1.0(3.0.0)
Platform M1 MacBook Pro 16
Output Device Apogee Duet 3

終了時に音量が保存されません。
音量が保存されない動作が正常化もしれませんが、保存されて欲しいと思ったのでIssue報告します。
仕様であればお手数掛けます。

**Comment by mosynthkey** [comment]
ありがとうございます。対応します！

**Comment by mosynthkey** [comment]
対応しました
