### ISSUE TITLE
Allow the play of multiple tracks

### ISSUE THREAD

**Issue by teopost** [mosynthkey/Melissa#46]
The function to separate tracks is very useful.
I suggest a small modification.
After separating the tracks it would be useful to be able to play the track of several instruments.
In this way it would be possible to play a song by excluding a single instrument and creating a backing track

**Comment by mosynthkey** [comment]
Thank you for the feedback and sorry for the late reply.
From v3.1.0, you can change the volume of each instrument after the separation.
