### ISSUE TITLE
ハングルのテキストが表示できません。(Unable to display Hangul text.)

### ISSUE THREAD

**Issue by NangmanGureum** [mosynthkey/Melissa#49]
英語がうまくないため、日本語に書きます。
英訳（DeepL使用）は下に書いています。
Since my English is not good, I write in Japanese.
English translation (using DeepL) is written below.

現在（v3.2.0）、ファイルやフォルダー（ディレクトリ）の名前の中にハングルが入ると、トーフで見える（枡のように見えることです。）現状があります。
例）`여자친구 - 시간을 달려서` -> `□□□□ - □□□ □□□`

最初は日本語でインストールした上で、それが原因だと思えアンインストールして英語にして再インストールしていましたが、それでも同じ現象が見られました。

多分Melissaの文字のエンコードが「Shift-JS」になったとか（Windows上で実行するとき、開いているフォルダーの位置が「バックスラッシュ」ではなく、「お金の円」で表示されているとか）、内部に使っているフォントが対応できないとか、または両方かもしれませんですね。

Currently (v3.2.0), when Hangul is included in the name of a file or folder (directory), it looks like a tofu (which means it looks like a square). There is a current situation.
Example: `여자친구 - 시간을 달려서` -> `□□□□ - □□□ □□□□`

At first I installed it in Japanese, and thinking that was the cause, I uninstalled it and reinstalled it in English, but I still saw the same phenomenon.

Maybe Melissa's character encoding is now "Shift-JS" (when running on Windows, the location of the open folder is displayed as a "money yen" instead of a "backslash"), or maybe the internal font is not compatible, or maybe both. Or both.

**Comment by mosynthkey** [comment]
@NangmanGureum
ご報告ありがとうございます！将来のバージョンで修正させていただきますね。
とりあえずの対応策として以下をお試しください。

1. Melissaを起動して、メニュー > 高度な設定 > 設定ファイルを表示
2. Melissaを終了
3. 1で表示されたSettings.jsonファイルをテキストエディタなどで開く
4.  "font_name" : "XXX" (XXXは任意のフォント名が書いてあります) の XXXを "Segoe UI"や"Malgun Gothic"などハングルを含んだフォント名に置き換える。 
5. Melissaを再度起動する

もしこれで成功しましたら、使えたフォントを教えていただけますと大変ありがたいです。
お手数をおかけしますが、よろしくお願いいたします。

**Comment by NangmanGureum** [comment]
> @NangmanGureum ご報告ありがとうございます！将来のバージョンで修正させていただきますね。 とりあえずの対応策として以下をお試しください。
> 
>     1. Melissaを起動して、メニュー > 高度な設定 > 設定ファイルを表示
> 
>     2. Melissaを終了
> 
>     3. 1で表示されたSettings.jsonファイルをテキストエディタなどで開く
> 
>     4. "font_name" : "XXX" (XXXは任意のフォント名が書いてあります) の XXXを "Segoe UI"や"Malgun Gothic"などハングルを含んだフォント名に置き換える。
> 
>     5. Melissaを再度起動する
> 
> 
> もしこれで成功しましたら、使えたフォントを教えていただけますと大変ありがたいです。 お手数をおかけしますが、よろしくお願いいたします。

助かりました！　ありがとうございます！
試しに使ったフォントは「[Spoqa Han Sans Neo](https://spoqa.github.io/spoqa-han-sans/)」です。

このフォントはSIF、つまりオープンソースです。そして、ハングルだけではなく、仮名や漢字も対応しています。更に、グラフィックデザイン的にも似合ってます。もし後で、フォントを搭載するなら、これがオススメだと思います。

**Comment by mosynthkey** [comment]
問題がとりあえず解決できたようでよかったです。
ありがとうございます！検討させていただきます。
